-- MySQL Script generated by MySQL Workbench
-- 06/07/16 19:15:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema herkansingv1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema herkansingv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `herkansingv1` DEFAULT CHARACTER SET utf8 ;
USE `herkansingv1` ;

-- -----------------------------------------------------
-- Table `herkansingv1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herkansingv1`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herkansingv1`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herkansingv1`.`teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `teamname` VARCHAR(45) NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `fk_teams_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_teams_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `herkansingv1`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herkansingv1`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herkansingv1`.`players` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `playername` VARCHAR(45) NULL,
  `rating` INT(2) NULL,
  `position` VARCHAR(45) NULL,
  `teams_team_id` INT NOT NULL,
  PRIMARY KEY (`player_id`),
  INDEX `fk_players_teams1_idx` (`teams_team_id` ASC),
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`teams_team_id`)
    REFERENCES `herkansingv1`.`teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
